spring.application.name=mobileback

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.platform = dataset
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode = always